package com.costwise.audit;

import static org.assertj.core.api.Assertions.assertThat;

import com.costwise.config.AuditPersistenceProperties;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.Instant;
import org.junit.jupiter.api.Test;

class JdbcAuditLogRepositoryTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    @Test
    void persistedRowsAreReadableAcrossRepositoryRecreation() throws Exception {
        Path dbDir = Files.createTempDirectory("audit-db");
        String jdbcUrl = "jdbc:h2:file:" + dbDir.resolve("audit-log").toString().replace("\\", "/")
                + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";

        createSchema(jdbcUrl);
        AuditPersistenceProperties properties = new AuditPersistenceProperties(null, jdbcUrl, "sa", "", "disable");

        AuditLogService writer = new AuditLogService(new JdbcAuditLogRepository(properties, objectMapper));
        writer.append(new AuditLogService.AppendCommand(
                "PJT-RESTART",
                "REVIEW",
                "planner",
                "writer",
                "submit",
                "workflow",
                "ok",
                JsonNodeFactory.instance.objectNode().put("token", "sb_secret_value"),
                JsonNodeFactory.instance.objectNode().put("authorization", "Bearer xxx.yyy.zzz"),
                Instant.parse("2026-04-21T01:02:03Z")));

        AuditLogService reader = new AuditLogService(new JdbcAuditLogRepository(properties, objectMapper));
        var response = reader.query(new AuditLogService.QueryCommand("PJT-RESTART", null, null, null, 10, null));

        assertThat(response.items()).hasSize(1);
        assertThat(response.items().getFirst().metadata().path("token").asText()).isEqualTo("***");
        assertThat(response.items().getFirst().requestContext().path("authorization").asText()).isEqualTo("***");
    }

    private void createSchema(String jdbcUrl) throws Exception {
        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "");
                Statement statement = connection.createStatement()) {
            statement.execute("""
                    create table if not exists audit_logs (
                      id bigint generated by default as identity primary key,
                      project_id varchar(128) not null,
                      event_type varchar(64) not null,
                      actor_role varchar(64) not null,
                      actor_id varchar(255) not null,
                      action varchar(64) not null,
                      target varchar(128) not null,
                      result varchar(64) not null,
                      metadata clob not null,
                      request_context clob not null,
                      occurred_at timestamp not null,
                      created_at timestamp not null
                    )
                    """);
        }
    }
}
