package com.costwise.workflow;

import static org.assertj.core.api.Assertions.assertThat;

import com.costwise.audit.AuditLogService;
import com.costwise.audit.JdbcAuditLogRepository;
import com.costwise.config.AuditPersistenceProperties;
import com.costwise.persistence.JdbcWorkflowStateRepository;
import com.costwise.service.PortfolioSummaryService;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import org.junit.jupiter.api.Test;

class ApprovalWorkflowPersistenceTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    @Test
    void workflowStateAndAuditHistorySurviveServiceRecreation() throws Exception {
        String jdbcUrl = "jdbc:h2:mem:workflow-restart;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";
        createSchema(jdbcUrl);
        AuditPersistenceProperties properties = new AuditPersistenceProperties(null, jdbcUrl, "sa", "", "disable");

        ApprovalWorkflowService writer = createService(properties);
        var first = writer.transition("3", "PLANNER", "SUBMIT", "기획 담당자", "검토 요청");
        assertThat(first.status()).isEqualTo("REVIEW");
        assertThat(first.lastAction()).isEqualTo("SUBMIT");

        ApprovalWorkflowService reader = createService(properties);
        var loaded = reader.loadWorkflow("3");

        assertThat(loaded.status()).isEqualTo("REVIEW");
        assertThat(loaded.lastAction()).isEqualTo("SUBMIT");
        assertThat(loaded.auditEvents())
                .anySatisfy(event -> {
                    assertThat(event.actor()).isEqualTo("기획 담당자");
                    assertThat(event.role()).isEqualTo("PLANNER");
                    assertThat(event.action()).isEqualTo("SUBMIT");
                    assertThat(event.detail()).isEqualTo("검토 요청");
                });
    }

    private ApprovalWorkflowService createService(AuditPersistenceProperties properties) {
        return new ApprovalWorkflowService(
                new PortfolioSummaryService(),
                new AuditLogService(new JdbcAuditLogRepository(properties, objectMapper)),
                new JdbcWorkflowStateRepository(properties));
    }

    private void createSchema(String jdbcUrl) throws Exception {
        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "");
                Statement statement = connection.createStatement()) {
            statement.execute("""
                    create table if not exists audit_logs (
                      id bigint generated by default as identity primary key,
                      project_id varchar(128) not null,
                      event_type varchar(64) not null,
                      actor_role varchar(64) not null,
                      actor_id varchar(255) not null,
                      action varchar(64) not null,
                      target varchar(128) not null,
                      result varchar(64) not null,
                      metadata clob not null,
                      request_context clob not null,
                      occurred_at timestamp not null,
                      created_at timestamp not null
                    )
                    """);
            statement.execute("""
                    create table if not exists workflow_states (
                      project_id varchar(128) primary key,
                      status varchar(32) not null,
                      last_action varchar(32) not null,
                      updated_at timestamp not null default current_timestamp
                    )
                    """);
        }
    }
}
