package com.costwise.api.workflow;

import static org.springframework.http.MediaType.APPLICATION_JSON;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.nimbusds.jose.jwk.source.ImmutableSecret;
import java.time.Instant;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Base64;
import java.util.List;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.oauth2.jose.jws.MacAlgorithm;
import org.springframework.security.oauth2.jwt.JwtClaimsSet;
import org.springframework.security.oauth2.jwt.JwtEncoder;
import org.springframework.security.oauth2.jwt.JwtEncoderParameters;
import org.springframework.security.oauth2.jwt.JwsHeader;
import org.springframework.security.oauth2.jwt.NimbusJwtEncoder;
import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest(properties = {
    "app.security.jwt.issuer-uri=https://example.supabase.co/auth/v1",
    "app.security.jwt.audience=authenticated",
    "app.security.jwt.secret-base64=c3VwYWJhc2UtYmVhcmVyLXRlc3Qtc2VjcmV0LXN1cHBvcnQ=",
    "app.persistence.jdbc-url=jdbc:h2:mem:auditlog-security;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE",
    "app.persistence.username=sa",
    "app.persistence.password="
})
@AutoConfigureMockMvc
class WorkflowControllerSecurityTest {

    private static final String ISSUER = "https://example.supabase.co/auth/v1";
    private static final String AUDIENCE = "authenticated";
    private static final String SECRET_BASE64 = "c3VwYWJhc2UtYmVhcmVyLXRlc3Qtc2VjcmV0LXN1cHBvcnQ=";

    @Autowired
    private MockMvc mockMvc;

    @BeforeEach
    void createSchema() throws Exception {
        try (Connection connection = DriverManager.getConnection(
                        "jdbc:h2:mem:auditlog-security;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE",
                        "sa",
                        "");
                Statement statement = connection.createStatement()) {
            statement.execute("drop table if exists audit_logs");
            statement.execute("""
                    create table audit_logs (
                      id bigint generated by default as identity primary key,
                      project_id varchar(128) not null,
                      event_type varchar(64) not null,
                      actor_role varchar(64) not null,
                      actor_id varchar(255) not null,
                      action varchar(64) not null,
                      target varchar(128) not null,
                      result varchar(64) not null,
                      metadata clob not null,
                      request_context clob not null,
                      occurred_at timestamp not null,
                      created_at timestamp not null
                    )
                    """);
            statement.execute("create index idx_audit_logs_project_id_id on audit_logs (project_id, id desc)");
            statement.execute("create index idx_audit_logs_project_event_id on audit_logs (project_id, event_type, id desc)");
            statement.execute("create index idx_audit_logs_project_occurred_id on audit_logs (project_id, occurred_at desc, id desc)");
        }
    }

    @Test
    void reviewEndpointWithoutBearerTokenReturnsUnauthorized() throws Exception {
        mockMvc.perform(post("/api/projects/14/review")
                        .contentType(APPLICATION_JSON)
                        .content("{\"action\":\"SUBMIT\",\"comment\":\"검토 요청\"}"))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void reviewEndpointRejectsExpiredBearerToken() throws Exception {
        Instant now = Instant.now();
        mockMvc.perform(post("/api/projects/14/review")
                        .header("Authorization", bearerToken(token("planner", ISSUER, AUDIENCE, now.minusSeconds(3600), now.minusSeconds(1800))))
                        .contentType(APPLICATION_JSON)
                        .content("{\"action\":\"SUBMIT\",\"comment\":\"만료 토큰\"}"))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void reviewEndpointRejectsWrongIssuer() throws Exception {
        Instant now = Instant.now();
        mockMvc.perform(post("/api/projects/14/review")
                        .header("Authorization", bearerToken(token("planner", "https://wrong.example.com/auth/v1", AUDIENCE, now, now.plusSeconds(3600))))
                        .contentType(APPLICATION_JSON)
                        .content("{\"action\":\"SUBMIT\",\"comment\":\"발급자 오류\"}"))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void reviewEndpointRejectsWrongAudience() throws Exception {
        Instant now = Instant.now();
        mockMvc.perform(post("/api/projects/14/review")
                        .header("Authorization", bearerToken(token("planner", ISSUER, "other-audience", now, now.plusSeconds(3600))))
                        .contentType(APPLICATION_JSON)
                        .content("{\"action\":\"SUBMIT\",\"comment\":\"대상자 오류\"}"))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void auditLogsRejectMissingToken() throws Exception {
        mockMvc.perform(get("/api/audit-logs?projectId=P-100"))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void auditLogsRequireProjectId() throws Exception {
        Instant now = Instant.now();
        mockMvc.perform(get("/api/audit-logs")
                        .header("Authorization", bearerToken(token("executive", ISSUER, AUDIENCE, now, now.plusSeconds(3600)))))
                .andExpect(status().isBadRequest());
    }

    @Test
    void auditLogsRejectPlannerRole() throws Exception {
        Instant now = Instant.now();
        mockMvc.perform(get("/api/audit-logs?projectId=P-100")
                        .header("Authorization", bearerToken(token("planner", ISSUER, AUDIENCE, now, now.plusSeconds(3600)))))
                .andExpect(status().isForbidden());
    }

    @Test
    void auditLogsAllowExecutiveRole() throws Exception {
        Instant now = Instant.now();
        mockMvc.perform(get("/api/audit-logs?projectId=P-100")
                        .header("Authorization", bearerToken(token("executive", ISSUER, AUDIENCE, now, now.plusSeconds(3600)))))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.items").isArray());
    }

    @Test
    void coreBusinessApisRejectAnonymousRequests() throws Exception {
        mockMvc.perform(get("/api/dashboard"))
                .andExpect(status().isUnauthorized());
        mockMvc.perform(get("/api/portfolio/summary"))
                .andExpect(status().isUnauthorized());
        mockMvc.perform(get("/api/cost-accounting/summary"))
                .andExpect(status().isUnauthorized());
        mockMvc.perform(get("/api/valuation-risk/projects/14"))
                .andExpect(status().isUnauthorized());
        mockMvc.perform(post("/api/compute")
                        .contentType(APPLICATION_JSON)
                        .content(validComputeRequest()))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void coreBusinessApisAllowAuthenticatedBusinessRoles() throws Exception {
        Instant now = Instant.now();
        for (String role : List.of("planner", "finance_reviewer", "executive")) {
            String authHeader = bearerToken(token(role, ISSUER, AUDIENCE, now, now.plusSeconds(3600)));

            mockMvc.perform(get("/api/dashboard").header("Authorization", authHeader))
                    .andExpect(status().isOk());
            mockMvc.perform(get("/api/portfolio/summary").header("Authorization", authHeader))
                    .andExpect(status().isOk());
            mockMvc.perform(get("/api/cost-accounting/summary").header("Authorization", authHeader))
                    .andExpect(status().isOk());
            mockMvc.perform(get("/api/valuation-risk/projects/14").header("Authorization", authHeader))
                    .andExpect(status().isOk());
            mockMvc.perform(post("/api/compute")
                            .header("Authorization", authHeader)
                            .contentType(APPLICATION_JSON)
                            .content(validComputeRequest()))
                    .andExpect(status().isOk());
        }
    }

    @Test
    void reviewEndpointAllowsPlannerToSubmit() throws Exception {
        Instant now = Instant.now();
        mockMvc.perform(post("/api/projects/14/review")
                        .header("Authorization", bearerToken(token("planner", ISSUER, AUDIENCE, now, now.plusSeconds(3600))))
                        .contentType(APPLICATION_JSON)
                        .content("{\"action\":\"SUBMIT\",\"comment\":\"검토 요청\"}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status").value("REVIEW"))
                .andExpect(jsonPath("$.lastAction").value("SUBMIT"));
    }

    private String bearerToken(String token) {
        return "Bearer " + token;
    }

    private String token(String role, String issuer, String audience, Instant issuedAt, Instant expiresAt) {
        SecretKey secretKey = new SecretKeySpec(Base64.getDecoder().decode(SECRET_BASE64), "HmacSHA256");
        JwtEncoder encoder = new NimbusJwtEncoder(new ImmutableSecret<>(secretKey));
        JwtClaimsSet claims = JwtClaimsSet.builder()
                .issuer(issuer)
                .subject("user-123")
                .audience(List.of(audience))
                .issuedAt(issuedAt)
                .expiresAt(expiresAt)
                .claim("email", role + "@example.com")
                .claim("role", role)
                .build();
        return encoder.encode(JwtEncoderParameters.from(JwsHeader.with(MacAlgorithm.HS256).build(), claims))
                .getTokenValue();
    }

    private String validComputeRequest() {
        return """
                {
                  "projectName": "테스트 프로젝트",
                  "discountRate": 0.08,
                  "departments": [
                    {"id": "HQ-1", "name": "기획본부"}
                  ],
                  "costPools": [
                    {
                      "name": "공통 인건비",
                      "amount": 1000000,
                      "allocationTargets": [
                        {"departmentId": "HQ-1", "departmentName": "기획본부", "weight": 1}
                      ]
                    }
                  ],
                  "cashFlows": [
                    {"periodNo": 0, "periodLabel": "초기", "yearLabel": "Y0", "netCashFlow": -1000000},
                    {"periodNo": 1, "periodLabel": "1년차", "yearLabel": "Y1", "netCashFlow": 1200000}
                  ]
                }
                """;
    }
}
