begin;

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  project_id text not null,
  event_type text not null,
  actor_role text not null,
  actor_id text not null,
  action text not null,
  target text not null,
  result text not null,
  metadata text not null,
  request_context text not null,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now(),
  check (length(trim(project_id)) > 0),
  check (length(trim(event_type)) > 0)
);

create index if not exists idx_audit_logs_project_id_id
  on audit_logs (project_id, id desc);

create index if not exists idx_audit_logs_project_event_id
  on audit_logs (project_id, event_type, id desc);

create index if not exists idx_audit_logs_project_event_lower_id
  on audit_logs (project_id, lower(event_type), id desc);

create index if not exists idx_audit_logs_project_occurred_id
  on audit_logs (project_id, occurred_at desc, id desc);

create or replace function reject_audit_logs_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'audit_logs is append-only';
end;
$$;

drop trigger if exists trg_audit_logs_append_only on audit_logs;

create trigger trg_audit_logs_append_only
before update or delete on audit_logs
for each row execute function reject_audit_logs_mutation();

commit;
